nome = str(input('Digite o seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculo é {}'.format(nome.upper()))
print('Seu nome em minúsculo é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
dividido = nome.split()
print('Seu primeiro nome tem ao todo {} letras'.format(len(dividido[0])))
